repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        language_version: python3.8
        additional_dependencies:
        -   flake8-bugbear==18.8.0
        -   flake8-builtins==1.4.1
        -   flake8-comprehensions==1.4.1
        -   flake8-tidy-imports==1.1.0
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.26.2
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
        language_version: python3.8
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
